# Generated by Django 5.1 on 2024-09-23 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0003_pedido_pedidoproducto"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="color",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="producto",
            name="dimensiones",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="pedidoproducto",
            name="cantidad",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="pedidoproducto",
            name="pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ventas.pedido"
            ),
        ),
        migrations.AlterField(
            model_name="pedidoproducto",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ventas.producto"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
